In [1]:
import duckdb
con = duckdb.connect("data.duckdb", read_only=True)

In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.max_rows", None)      # show all rows
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [4]:
#customer distribution
query = "Describe customers"
df = con.execute(query).df()
print(df)

                           column_name column_type null   key default extra
0                              bank_id     VARCHAR  YES  None    None  None
1                            bank_name     VARCHAR  YES  None    None  None
2                          customer_id     VARCHAR  YES  None    None  None
3                       account_number     VARCHAR  YES  None    None  None
4                            full_name     VARCHAR  YES  None    None  None
5                        customer_type     VARCHAR  YES  None    None  None
6                     title_salutation     VARCHAR  YES  None    None  None
7                             forename     VARCHAR  YES  None    None  None
8                    forename_previous     VARCHAR  YES  None    None  None
9                          middle_name     VARCHAR  YES  None    None  None
10                             surname     VARCHAR  YES  None    None  None
11                    surname_previous     VARCHAR  YES  None    None  None
12                       date_of_birth        DATE  YES  None    None  None
13                         nationality     VARCHAR  YES  None    None  None
14                country_of_residence     VARCHAR  YES  None    None  None
15                          occupation     VARCHAR  YES  None    None  None
16                              gender     VARCHAR  YES  None    None  None
17                         id_doc_type     VARCHAR  YES  None    None  None
18                       id_doc_number      BIGINT  YES  None    None  None
19                  id_doc_expiry_date        DATE  YES  None    None  None
20                        trading_name     VARCHAR  YES  None    None  None
21               company_name_previous     VARCHAR  YES  None    None  None
22       company_registration_doc_type     VARCHAR  YES  None    None  None
23         company_registration_number     VARCHAR  YES  None    None  None
24               date_of_incorporation        DATE  YES  None    None  None
25                        company_type     VARCHAR  YES  None    None  None
26   country_of_incorporation_business     VARCHAR  YES  None    None  None
27  country_primary_operation_business     VARCHAR  YES  None    None  None
28                    primary_industry     VARCHAR  YES  None    None  None
29                       annual_income      BIGINT  YES  None    None  None
30              annual_income_currency     VARCHAR  YES  None    None  None
31             primary_source_of_funds     VARCHAR  YES  None    None  None
32                             address     VARCHAR  YES  None    None  None
33                            postcode     VARCHAR  YES  None    None  None
34                               email     VARCHAR  YES  None    None  None
35                        phone_number     VARCHAR  YES  None    None  None
36                    name_change_date        DATE  YES  None    None  None
37                       last_kyc_date        DATE  YES  None    None  None
38                          start_date        DATE  YES  None    None  None
39                            end_date        DATE  YES  None    None  None

In [5]:
#customer distribution
query = "Select distinct bank_name from customers"
df = con.execute(query).df()
print(df)

             bank_name
0  Focus South Banking
1   Berry Western Bank

In [11]:
#customer distribution
query = "Select distinct count(full_name) from customers limit 25"
df = con.execute(query).df()
print(df)

   count(full_name)
0            229463

In [4]:
#Income by occupation
query = """
SELECT occupation,COUNT(*) as customer_count,ROUND(AVG(annual_income), 2) as avg_income,ROUND(MIN(annual_income), 2) as min_income,ROUND(MAX(annual_income), 2) as max_income
FROM customers
WHERE annual_income IS NOT NULL
GROUP BY occupation
ORDER BY avg_income DESC
LIMIT 10
"""
df = con.execute(query).df()
print(df)

                                                    occupation  \
0                                                          NaN
1                             Corporate managers and directors
2  Science, research, engineering and technology professionals
3             Business, media and public service professionals
4          Business and public service associate professionals
5                               Protective service occupations
6                                         Health professionals
7                       Teaching and educational professionals
8              Skilled metal, electrical and electronic trades
9                               Other managers and proprietors

   customer_count  avg_income  min_income  max_income
0           14962   621526.01           0    49632800
1           11449    52053.88        3600      199200
2            6622    43909.66           0      117000
3            7677    41324.72        6500      130900
4           10999    36884.45        3800      165900
5            1846    36719.99           0      143400
6            7713    34700.69           0      190300
7            7606    33815.96           0       88200
8            4524    32197.37       11700       65700
9            2318    30146.33        2500      117900

In [13]:
#total customers
query = "SELECT COUNT(*) as total_customers FROM customers"
con.execute(query).df()

   total_customers
0           229463

In [14]:
# What are the different banks in the dataset?
query = "SELECT DISTINCT bank_name FROM customers"
con.execute(query).df()

             bank_name
0  Focus South Banking
1   Berry Western Bank

In [15]:
#What is the highest annual income in the dataset?
query = "SELECT MAX(annual_income) as highest_income FROM customers"
con.execute(query).df()

   highest_income
0        49632800

In [13]:
query = "SELECT*FROM customers LIMIT 10"
con.execute(query).df()

,bank_id,bank_name,customer_id,account_number,full_name,customer_type,title_salutation,forename,forename_previous,middle_name,surname,surname_previous,date_of_birth,nationality,country_of_residence,occupation,gender,id_doc_type,id_doc_number,id_doc_expiry_date,trading_name,company_name_previous,company_registration_doc_type,company_registration_number,date_of_incorporation,company_type,country_of_incorporation_business,country_primary_operation_business,primary_industry,annual_income,annual_income_currency,primary_source_of_funds,address,postcode,email,phone_number,name_change_date,last_kyc_date,start_date,end_date
0,FOCSGB,Focus South Banking,1000158794,FOCSGB00000000150724,Scott Palmer,individual,Mr,Scott,None,NaN,Palmer,None,1997-03-31,British,GB,Administrative occupations,M,Passport,1740272659,2027-10-18,None,None,None,None,NaT,None,None,None,None,32900,GBP,Salary,"678 Chapman Land, Staple Hill, South Gloucestershire",BS16 5JY,scottpalmer966@gmail.synth,07653133240,NaT,2023-04-15,2021-09-06,NaT
1,BWBAGB,Berry Western Bank,1000043545,BWBAGB00000000065507,Megan Tran Schultz Thompson,individual,Mrs,Megan,None,Tran Schultz,Thompson,None,1956-02-03,British,GB,Retired,F,Passport,9384807833,2023-11-15,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"1437 Ryan Rue Apt. 947, Cromarty Firth, Highland",IV18 0LF,megantranschultzthompson781@yahoo.synth,07218140433,NaT,2017-07-10,1983-03-25,NaT
2,FOCSGB,Focus South Banking,1000055016,FOCSGB00000000046946,Kimberly Tran,individual,Mrs,Kimberly,None,NaN,Tran,None,1927-09-12,British,GB,Retired,F,Passport,2857056644,2016-01-28,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"570 Jennings Trace Apt. 513, Abbey Wood, Greenwich",SE2 9JT,kimberlytran159@hotmail.synth,07811328126,NaT,2016-02-29,1977-08-14,NaT
3,FOCSGB,Focus South Banking,1000126320,FOCSGB00000000118250,Anthony Garcia,individual,Mr,Anthony,None,NaN,Garcia,None,1991-10-03,British,GB,"Skilled metal, electrical and electronic trades",M,Passport,353316666,2020-11-25,None,None,None,None,NaT,None,None,None,None,31600,GBP,Salary,"461 King Bypass Suite 159, East Berwickshire, Scottish Borders",TD14 5SZ,anthonygarcia26@gmail.synth,07749518211,NaT,2021-01-23,2015-10-06,NaT
4,FOCSGB,Focus South Banking,1000102208,FOCSGB00000000094138,John Holland Sexton,individual,Mr,John,None,Holland,Sexton,None,1982-04-26,British,GB,Corporate managers and directors,M,Passport,9911876883,2010-04-30,None,None,None,None,NaT,None,None,None,None,89800,GBP,Salary,"13743 Patel Shores Suite 508, Hucknall West, Ashfield",NG15 6FU,johnhollandsexton987@yahoo.synth,07748621937,NaT,2017-07-06,2008-12-15,2025-10-25
5,FOCSGB,Focus South Banking,1000052823,FOCSGB00000000044753,Mark Forbes,individual,Mr,Mark,None,NaN,Forbes,None,1924-10-30,British,GB,Retired,M,Passport,6574843910,2013-10-01,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"678 David Hills Suite 813, Grangemouth, Falkirk",FK3 8HR,markforbes49@hotmail.synth,07226905792,NaT,2018-06-21,1972-12-05,NaT
6,FOCSGB,Focus South Banking,1000125842,FOCSGB00000000117772,Stanley Russell,individual,Mr,Stanley,None,NaN,Russell,None,1983-06-09,British,GB,Business and public service associate professionals,M,Passport,1267549145,2023-11-23,None,None,None,None,NaT,None,None,None,None,35800,GBP,Salary,"51835 Wade Stravenue, Westhoughton North, Bolton",BL5 3NN,stanleyrussell657@yahoo.synth,07196918883,NaT,2018-06-11,2015-08-29,NaT
7,FOCSGB,Focus South Banking,1000085038,FOCSGB00000000076968,Tanya Martinez,individual,Mrs,Tanya,None,NaN,Martinez,None,1977-05-22,British,GB,Unemployed,F,Passport,9593528501,2025-08-04,None,None,None,None,NaT,None,None,None,None,3900,GBP,State benefits,"50469 David Circle Apt. 037, Tavistock North, West Devon",PL19 0DT,tanyamartinez594@hotmail.synth,07010525733,NaT,2019-03-10,2002-02-02,NaT
8,FOCSGB,Focus South Banking,1000081200,FOCSGB00000000073130,Frances Brown,individual,Mrs,Frances,None,NaN,Brown,None,1975-01-15,British,GB,Caring personal service occupations,F,Passport,3536684510,2022-08-02,None,None,None,None,NaT,None,None,None,None,10600,GBP,Salary,"204 Jenkins Walk, Stotfold, Central Bedfordshire",SG5 4GX,francesbrown576@hotmail.synth,07331169006,NaT,2016-08-13,2000-03-27,NaT
9,FOCSGB,Focus South Banking,1000095603,FOCSGB00000000087533,Jeanne Grant,individual,Dr,Jeanne,None,NaN,Grant,None,1981-04-13,British,GB,Customer service occupations,F,Passport,1133610244,2029-05-28,None,None,None,None,NaT,None,None,None,None,35600,GBP,Salary,"23109 Dylan Forge, Pinner, Harrow",HA5 3LA,jeannegrant654@yahoo.synth,07730914459,NaT,2015-10-06,2006-07-30,NaT

In [20]:
query = """
SELECT 
    nationality, 
    COUNT(*) as count
FROM customers
GROUP BY nationality
ORDER BY count DESC
"""
con.execute(query).df()

                       nationality   count
0                          British  194617
1                              NaN   14962
2                           Poland    2887
3                          Romania    1412
4                            India    1162
5              Republic.of.Ireland    1024
6                            Italy     984
7                         Portugal     686
8                        Lithuania     660
9                           France     629
10                        Pakistan     603
11                           Spain     587
12        United.States.of.America     541
13                         Germany     459
14                           China     453
15                     Netherlands     385
16                         Nigeria     340
17                        Bulgaria     331
18                      Bangladesh     330
19                          Latvia     307
20                       Australia     296
21                    South.Africa     273
22                          Greece     268
23                     Philippines     262
24                        Slovakia     246
25                          Turkey     227
26                         Hungary     218
27                          Brazil     218
28                           Nepal     169
29                       Sri.Lanka     160
30                  Czech.Republic     153
31                          Sweden     153
32                        Zimbabwe     147
33                     New.Zealand     145
34                          Canada     140
35                           Ghana     135
36                           Japan     134
37                         Somalia     125
38                           Syria     122
39                            Iraq     116
40                         Jamaica     112
41                     Afghanistan     111
42                        Malaysia     110
43                            Iran     104
44                         Denmark      98
45                          Russia      96
46                        Thailand      96
47                         Albania      92
48                         Belgium      73
49                         Eritrea      73
50                         Ukraine      63
51                         Finland      61
52                         Austria      53
53                           Kenya      51
54                           Sudan      51
55                          Norway      49
56                     Switzerland      48
57                         Estonia      44
58                           Egypt      43
59                         Algeria      40
60                         Vietnam      39
61                        Colombia      38
62                         Moldova      37
63                       Indonesia      37
64     Congo..Democratic.Republic.      36
65                       Singapore      36
66                    Saudi.Arabia      35
67         Cyprus..European.Union.      35
68                     Gambia..The      34
69                       Mauritius      34
70                          Uganda      32
71                        Ethiopia      32
72                       Venezuela      30
73                        Cameroon      30
74                           Libya      28
75                     South.Korea      26
76                         Croatia      26
77                         Morocco      23
78                           Congo      22
79                          Mexico      21
80                           Malta      20
81                         Lebanon      19
82                     Ivory.Coast      18
83                          Kuwait      17
84                    Sierra.Leone      16
85                          Zambia      11
86                      Azerbaijan      11
87                        St.Lucia      10
88                          Serbia      10
89             Trinidad.and.Tobago       9
90                        Mongolia       9
91                         Ecuador       9
92                          Israel       9
93                          Panama       8
94                            Peru       8
95                          Taiwan       8
96             Antigua.and.Barbuda       7
97                          Malawi       7
98                      Uzbekistan       6
99                      Seychelles       6
100           United.Arab.Emirates       6
101                        Armenia       5
102                      Macedonia       5
103                      Argentina       5
104             Dominican.Republic       5
105                         Jordan       5
106                        Bolivia       5
107                         Kosovo       5
108                          Qatar       5
109                   Sudan..South       5
110                    North.Korea       4
111  St.Vincent.and.the.Grenadines       4
112                       Slovenia       4
113                       Barbados       3
114                   Turkmenistan       3
115                         Guinea       3
116                           Fiji       2
117                        Tunisia       2
118                         Angola       2
119       Central.African.Republic       1
120                     Costa.Rica       1

In [4]:
query = "SELECT * FROM customers limit 10"
con.execute(query).df()

,bank_id,bank_name,customer_id,account_number,full_name,customer_type,title_salutation,forename,forename_previous,middle_name,surname,surname_previous,date_of_birth,nationality,country_of_residence,occupation,gender,id_doc_type,id_doc_number,id_doc_expiry_date,trading_name,company_name_previous,company_registration_doc_type,company_registration_number,date_of_incorporation,company_type,country_of_incorporation_business,country_primary_operation_business,primary_industry,annual_income,annual_income_currency,primary_source_of_funds,address,postcode,email,phone_number,name_change_date,last_kyc_date,start_date,end_date
0,FOCSGB,Focus South Banking,1000158794,FOCSGB00000000150724,Scott Palmer,individual,Mr,Scott,None,NaN,Palmer,None,1997-03-31,British,GB,Administrative occupations,M,Passport,1740272659,2027-10-18,None,None,None,None,NaT,None,None,None,None,32900,GBP,Salary,"678 Chapman Land, Staple Hill, South Gloucestershire",BS16 5JY,scottpalmer966@gmail.synth,07653133240,NaT,2023-04-15,2021-09-06,NaT
1,BWBAGB,Berry Western Bank,1000043545,BWBAGB00000000065507,Megan Tran Schultz Thompson,individual,Mrs,Megan,None,Tran Schultz,Thompson,None,1956-02-03,British,GB,Retired,F,Passport,9384807833,2023-11-15,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"1437 Ryan Rue Apt. 947, Cromarty Firth, Highland",IV18 0LF,megantranschultzthompson781@yahoo.synth,07218140433,NaT,2017-07-10,1983-03-25,NaT
2,FOCSGB,Focus South Banking,1000055016,FOCSGB00000000046946,Kimberly Tran,individual,Mrs,Kimberly,None,NaN,Tran,None,1927-09-12,British,GB,Retired,F,Passport,2857056644,2016-01-28,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"570 Jennings Trace Apt. 513, Abbey Wood, Greenwich",SE2 9JT,kimberlytran159@hotmail.synth,07811328126,NaT,2016-02-29,1977-08-14,NaT
3,FOCSGB,Focus South Banking,1000126320,FOCSGB00000000118250,Anthony Garcia,individual,Mr,Anthony,None,NaN,Garcia,None,1991-10-03,British,GB,"Skilled metal, electrical and electronic trades",M,Passport,353316666,2020-11-25,None,None,None,None,NaT,None,None,None,None,31600,GBP,Salary,"461 King Bypass Suite 159, East Berwickshire, Scottish Borders",TD14 5SZ,anthonygarcia26@gmail.synth,07749518211,NaT,2021-01-23,2015-10-06,NaT
4,FOCSGB,Focus South Banking,1000102208,FOCSGB00000000094138,John Holland Sexton,individual,Mr,John,None,Holland,Sexton,None,1982-04-26,British,GB,Corporate managers and directors,M,Passport,9911876883,2010-04-30,None,None,None,None,NaT,None,None,None,None,89800,GBP,Salary,"13743 Patel Shores Suite 508, Hucknall West, Ashfield",NG15 6FU,johnhollandsexton987@yahoo.synth,07748621937,NaT,2017-07-06,2008-12-15,2025-10-25
5,FOCSGB,Focus South Banking,1000052823,FOCSGB00000000044753,Mark Forbes,individual,Mr,Mark,None,NaN,Forbes,None,1924-10-30,British,GB,Retired,M,Passport,6574843910,2013-10-01,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"678 David Hills Suite 813, Grangemouth, Falkirk",FK3 8HR,markforbes49@hotmail.synth,07226905792,NaT,2018-06-21,1972-12-05,NaT
6,FOCSGB,Focus South Banking,1000125842,FOCSGB00000000117772,Stanley Russell,individual,Mr,Stanley,None,NaN,Russell,None,1983-06-09,British,GB,Business and public service associate professionals,M,Passport,1267549145,2023-11-23,None,None,None,None,NaT,None,None,None,None,35800,GBP,Salary,"51835 Wade Stravenue, Westhoughton North, Bolton",BL5 3NN,stanleyrussell657@yahoo.synth,07196918883,NaT,2018-06-11,2015-08-29,NaT
7,FOCSGB,Focus South Banking,1000085038,FOCSGB00000000076968,Tanya Martinez,individual,Mrs,Tanya,None,NaN,Martinez,None,1977-05-22,British,GB,Unemployed,F,Passport,9593528501,2025-08-04,None,None,None,None,NaT,None,None,None,None,3900,GBP,State benefits,"50469 David Circle Apt. 037, Tavistock North, West Devon",PL19 0DT,tanyamartinez594@hotmail.synth,07010525733,NaT,2019-03-10,2002-02-02,NaT
8,FOCSGB,Focus South Banking,1000081200,FOCSGB00000000073130,Frances Brown,individual,Mrs,Frances,None,NaN,Brown,None,1975-01-15,British,GB,Caring personal service occupations,F,Passport,3536684510,2022-08-02,None,None,None,None,NaT,None,None,None,None,10600,GBP,Salary,"204 Jenkins Walk, Stotfold, Central Bedfordshire",SG5 4GX,francesbrown576@hotmail.synth,07331169006,NaT,2016-08-13,2000-03-27,NaT
9,FOCSGB,Focus South Banking,1000095603,FOCSGB00000000087533,Jeanne Grant,individual,Dr,Jeanne,None,NaN,Grant,None,1981-04-13,British,GB,Customer service occupations,F,Passport,1133610244,2029-05-28,None,None,None,None,NaT,None,None,None,None,35600,GBP,Salary,"23109 Dylan Forge, Pinner, Harrow",HA5 3LA,jeannegrant654@yahoo.synth,07730914459,NaT,2015-10-06,2006-07-30,NaT

In [7]:
query = "SELECT distinct bank_name from customers"
con.execute(query).df()

             bank_name
0   Berry Western Bank
1  Focus South Banking

In [16]:
query = "SELECT * from customers where occupation='Retired' limit 10"
con.execute(query).df()

,bank_id,bank_name,customer_id,account_number,full_name,customer_type,title_salutation,forename,forename_previous,middle_name,surname,surname_previous,date_of_birth,nationality,country_of_residence,occupation,gender,id_doc_type,id_doc_number,id_doc_expiry_date,trading_name,company_name_previous,company_registration_doc_type,company_registration_number,date_of_incorporation,company_type,country_of_incorporation_business,country_primary_operation_business,primary_industry,annual_income,annual_income_currency,primary_source_of_funds,address,postcode,email,phone_number,name_change_date,last_kyc_date,start_date,end_date
0,BWBAGB,Berry Western Bank,1000043545,BWBAGB00000000065507,Megan Tran Schultz Thompson,individual,Mrs,Megan,None,Tran Schultz,Thompson,None,1956-02-03,British,GB,Retired,F,Passport,9384807833,2023-11-15,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"1437 Ryan Rue Apt. 947, Cromarty Firth, Highland",IV18 0LF,megantranschultzthompson781@yahoo.synth,07218140433,NaT,2017-07-10,1983-03-25,NaT
1,FOCSGB,Focus South Banking,1000055016,FOCSGB00000000046946,Kimberly Tran,individual,Mrs,Kimberly,None,NaN,Tran,None,1927-09-12,British,GB,Retired,F,Passport,2857056644,2016-01-28,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"570 Jennings Trace Apt. 513, Abbey Wood, Greenwich",SE2 9JT,kimberlytran159@hotmail.synth,07811328126,NaT,2016-02-29,1977-08-14,NaT
2,FOCSGB,Focus South Banking,1000052823,FOCSGB00000000044753,Mark Forbes,individual,Mr,Mark,None,NaN,Forbes,None,1924-10-30,British,GB,Retired,M,Passport,6574843910,2013-10-01,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"678 David Hills Suite 813, Grangemouth, Falkirk",FK3 8HR,markforbes49@hotmail.synth,07226905792,NaT,2018-06-21,1972-12-05,NaT
3,FOCSGB,Focus South Banking,1000178657,FOCSGB00000000170587,Victoria Davies Phelps,individual,Mrs,Victoria,None,Davies,Phelps,None,1950-11-05,British,GB,Retired,F,Passport,419740206,2011-08-10,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"2632 Alicia Springs, Manchester",M14 5WT,victoriadaviesphelps43@yahoo.synth,07973861784,NaT,2022-12-15,2024-01-14,NaT
4,FOCSGB,Focus South Banking,1000146467,FOCSGB00000000138397,Kimberly Torres Davis Barker,individual,Mrs,Kimberly,None,Torres Davis,Barker,None,1949-06-02,British,GB,Retired,F,Passport,5867299858,2021-12-21,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"604 Miller Track, Blagreaves, Derby",DE23 2XL,kimberlytorresdavisbarker71@hotmail.synth,07931939018,NaT,2024-05-28,2019-10-13,NaT
5,FOCSGB,Focus South Banking,1000111775,FOCSGB00000000103705,Jeffrey Wilkinson,individual,Mr,Jeffrey,None,NaN,Wilkinson,None,1952-08-06,British,GB,Retired,M,Passport,6093851086,2012-10-03,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"744 Benson Crossroad Apt. 729, Midlothian West, Midlothian",EH20 9LA,jeffreywilkinson263@yahoo.synth,07692648111,NaT,2017-07-06,2011-12-29,NaT
6,BWBAGB,Berry Western Bank,1000101304,BWBAGB00000000123266,Edward Hunter,individual,Mr,Edward,None,NaN,Hunter,None,1947-10-29,British,GB,Retired,M,Passport,7351529826,2016-11-28,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"265 Julie Views Apt. 637, Westbourne, Brighton",BN3 4HR,edwardhunter854@hotmail.synth,07663584887,NaT,2025-09-24,2024-03-02,NaT
7,FOCSGB,Focus South Banking,1000190069,FOCSGB00000000181999,Zoe Gaines,individual,Mrs,Zoe,None,NaN,Gaines,None,1933-02-20,British,GB,Retired,F,Passport,3395471401,2016-12-19,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"270 Salazar Vista, Paisley Southwest, Renfrewshire",PA2 8JW,zoegaines77@gmail.synth,07285132119,NaT,2023-10-27,2024-10-11,NaT
8,FOCSGB,Focus South Banking,1000057181,FOCSGB00000000049111,David Rivas,individual,Mr,David,None,NaN,Rivas,None,1951-08-14,British,GB,Retired,M,Passport,9202956997,2010-08-27,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"7286 Willis Stravenue, Orton Waterville, Peterborough",PE2 5ST,davidrivas861@gmail.synth,07354613586,NaT,2015-10-27,1981-03-13,NaT
9,BWBAGB,Berry Western Bank,1000059969,BWBAGB00000000081931,Tiffany Mendoza Barnes,individual,Mrs,Tiffany,None,Mendoza,Barnes,None,1941-09-12,British,GB,Retired,F,Passport,2814352534,2027-05-29,None,None,None,None,NaT,None,None,None,None,6700,GBP,Pension,"24756 Ruth Shores, East Preston, Arun",BN16 1LQ,tiffanymendozabarnes346@gmail.synth,07417893807,NaT,2017-05-09,2006-12-04,NaT

In [ ]:
query = "SELECT * from customers where occupation='Retired' limit 10"
con.execute(query).df()

In [20]:
query = "Describe customers"
con.execute(query).df()

                           column_name column_type null   key default extra
0                              bank_id     VARCHAR  YES  None    None  None
1                            bank_name     VARCHAR  YES  None    None  None
2                          customer_id     VARCHAR  YES  None    None  None
3                       account_number     VARCHAR  YES  None    None  None
4                            full_name     VARCHAR  YES  None    None  None
5                        customer_type     VARCHAR  YES  None    None  None
6                     title_salutation     VARCHAR  YES  None    None  None
7                             forename     VARCHAR  YES  None    None  None
8                    forename_previous     VARCHAR  YES  None    None  None
9                          middle_name     VARCHAR  YES  None    None  None
10                             surname     VARCHAR  YES  None    None  None
11                    surname_previous     VARCHAR  YES  None    None  None
12                       date_of_birth        DATE  YES  None    None  None
13                         nationality     VARCHAR  YES  None    None  None
14                country_of_residence     VARCHAR  YES  None    None  None
15                          occupation     VARCHAR  YES  None    None  None
16                              gender     VARCHAR  YES  None    None  None
17                         id_doc_type     VARCHAR  YES  None    None  None
18                       id_doc_number      BIGINT  YES  None    None  None
19                  id_doc_expiry_date        DATE  YES  None    None  None
20                        trading_name     VARCHAR  YES  None    None  None
21               company_name_previous     VARCHAR  YES  None    None  None
22       company_registration_doc_type     VARCHAR  YES  None    None  None
23         company_registration_number     VARCHAR  YES  None    None  None
24               date_of_incorporation        DATE  YES  None    None  None
25                        company_type     VARCHAR  YES  None    None  None
26   country_of_incorporation_business     VARCHAR  YES  None    None  None
27  country_primary_operation_business     VARCHAR  YES  None    None  None
28                    primary_industry     VARCHAR  YES  None    None  None
29                       annual_income      BIGINT  YES  None    None  None
30              annual_income_currency     VARCHAR  YES  None    None  None
31             primary_source_of_funds     VARCHAR  YES  None    None  None
32                             address     VARCHAR  YES  None    None  None
33                            postcode     VARCHAR  YES  None    None  None
34                               email     VARCHAR  YES  None    None  None
35                        phone_number     VARCHAR  YES  None    None  None
36                    name_change_date        DATE  YES  None    None  None
37                       last_kyc_date        DATE  YES  None    None  None
38                          start_date        DATE  YES  None    None  None
39                            end_date        DATE  YES  None    None  None

In [21]:
# How many total customers are there?
query = "SELECT distinct Count(customer_id) from customers"
con.execute(query).df()

   count(customer_id)
0              229463

In [ ]:
# Find high earners (income > 50000)

In [15]:
# What are the sources of funds?
query = "Select distinct primary_source_of_funds,count(*) as funds from customers where primary_source_of_funds is not null Group By primary_source_of_funds, Order by funds DESC"
con.execute(query).df()

  primary_source_of_funds   funds
0                  Salary  134407
1                 Pension   44351
2          State benefits   32741
3       Business Activity   14962
4         Student incomes    2498
5  Salary and investments     280
6    Salary and dividends     224

In [13]:
query = """
SELECT 
    primary_source_of_funds, 
    COUNT(*) as count
FROM customers
WHERE primary_source_of_funds IS NOT NULL
GROUP BY primary_source_of_funds
ORDER BY count DESC
"""
con.execute(query).df()

  primary_source_of_funds   count
0                  Salary  134407
1                 Pension   44351
2          State benefits   32741
3       Business Activity   14962
4         Student incomes    2498
5  Salary and investments     280
6    Salary and dividends     224

In [8]:
# List all occupations with counts
query = "SELECT occupation,count(*) as occupation_status from customers Group by Occupation"
con.execute(query).df()

,occupation,occupation_status
0,Transport and mobile machine drivers and operatives,4016
1,"Leisure, travel and related personal service occupations",2125
2,"Science, engineering and technology associate professionals",3371
3,Customer service occupations,2870
4,Skilled construction and building trades,1512
5,NaN,14962
6,Unemployed,32741
7,Elementary administration and service occupations,13546
8,"Business, media and public service professionals",7677
9,Secretarial and related occupations,3232
10,Corporate managers and directors,11449
11,"Textiles, printing and other skilled trades",2534
12,Administrative occupations,12764
13,Retired,44351
14,Business and public service associate professionals,10999
15,"Culture, media and sports occupations",1388
16,"Process, plant and machine operatives",3628
17,Student,2498
18,Caring personal service occupations,10703
19,"Science, research, engineering and technology professionals",6622
20,"Skilled metal, electrical and electronic trades",4524
21,Skilled agricultural and related trades,389
22,Health professionals,7713
23,Other managers and proprietors,2318
24,Protective service occupations,1846
25,Sales occupations,8238
26,Teaching and educational professionals,7606
27,Elementary trades and related occupations,1954
28,Health and social care associate professionals,1887

In [ ]:
query = """
SELECT gender, COUNT(*) as count FROM customers 
WHERE occupation='Retired' AND nationality='British' 
GROUP BY gender
"""
con.execute(query).df()

  gender  count
0      F  23809
1      M  16838

In [66]:
query = "SELECT distinct Count(customer_id) from customers"
con.execute(query).df()

   count(customer_id)
0              229463

In [23]:
# What banks are in the dataset?
query = "SELECT distinct bank_name from customers"
con.execute(query).df()

             bank_name
0  Focus South Banking
1   Berry Western Bank

In [31]:
# How many customers does each bank have?
query = "SELECT distinct bank_name,count(customer_id) from customers group by bank_name"
con.execute(query).df()

             bank_name  count(customer_id)
0   Berry Western Bank               74979
1  Focus South Banking              154484

In [43]:
# How many male and female customers?
query = "SELECT gender, count(gender) from customers where gender is not null group by gender order by count(gender)"
con.execute(query).df()

  gender  count(gender)
0      M         104015
1      F         110486

In [48]:
#  What is the highest income?
query = "SELECT max(annual_income) from customers"
con.execute(query).df()

   max(annual_income)
0            49632800

In [55]:
# What is the lowest income?
query = "SELECT full_name, annual_income from customers where annual_income !=0 order by annual_income ASC limit 1"
con.execute(query).df()

  full_name  annual_income
0  Chan LTD            100

In [51]:
query = "SELECT min(annual_income) as min_income FROM customers"
con.execute(query).df()

   min_income
0           0

In [60]:
#  What is the average income?
query = "SELECT round(avg(annual_income),2) as avg_income  FROM customers"
con.execute(query).df()

   avg_income
0    58947.29

In [64]:
# How many retired customers?
query = "SELECT full_name from customers where occupation='Retired' limit 10"
con.execute(query).df()

                      full_name
0   Megan Tran Schultz Thompson
1                Kimberly  Tran
2                  Mark  Forbes
3        Victoria Davies Phelps
4  Kimberly Torres Davis Barker
5            Jeffrey  Wilkinson
6                Edward  Hunter
7                   Zoe  Gaines
8                  David  Rivas
9        Tiffany Mendoza Barnes

In [ ]:
# ?just tell me how many are retired male and female british
query = "SELECT full_name, annual_income"
con.execute(query).df()

In [61]:
# Show first 10 customers
query = "SELECT full_name  FROM customers limit 10"
con.execute(query).df()

                     full_name
0                Scott  Palmer
1  Megan Tran Schultz Thompson
2               Kimberly  Tran
3              Anthony  Garcia
4          John Holland Sexton
5                 Mark  Forbes
6             Stanley  Russell
7              Tanya  Martinez
8               Frances  Brown
9                Jeanne  Grant