# SQL Practice with Indian Banking Data
## Interactive Jupyter Notebook for SQL Queries

In [4]:
import duckdb
import pandas as pd

# Connect to database
conn = duckdb.connect('indian_banking.duckdb')

# Helper function to run queries
def query(sql):
    return conn.execute(sql).fetchdf()

print("✓ Connected to database!")
print(f"Total customers: {query('SELECT COUNT(*) as count FROM customers')['count'][0]:,}")

✓ Connected to database!
Total customers: 100,000

In [2]:
query("describe customers")

                column_name column_type null   key default extra
0               customer_id     VARCHAR  YES  None    None  None
1                   bank_id     VARCHAR  YES  None    None  None
2                 bank_name     VARCHAR  YES  None    None  None
3            account_number     VARCHAR  YES  None    None  None
4                     title     VARCHAR  YES  None    None  None
5                first_name     VARCHAR  YES  None    None  None
6               middle_name     VARCHAR  YES  None    None  None
7                 last_name     VARCHAR  YES  None    None  None
8                 full_name     VARCHAR  YES  None    None  None
9                    gender     VARCHAR  YES  None    None  None
10            date_of_birth        DATE  YES  None    None  None
11                    email     VARCHAR  YES  None    None  None
12                    phone     VARCHAR  YES  None    None  None
13                  address     VARCHAR  YES  None    None  None
14               occupation     VARCHAR  YES  None    None  None
15            annual_income      BIGINT  YES  None    None  None
16  primary_source_of_funds     VARCHAR  YES  None    None  None
17             account_type     VARCHAR  YES  None    None  None
18          account_balance      DOUBLE  YES  None    None  None
19             credit_score      BIGINT  YES  None    None  None
20           account_status     VARCHAR  YES  None    None  None
21             created_date        DATE  YES  None    None  None
22    last_transaction_date        DATE  YES  None    None  None
23   transactions_per_month      BIGINT  YES  None    None  None

In [12]:
query("SELECT gender, COUNT(*) AS total_customers FROM bank_customers GROUP BY gender")

CatalogException: Catalog Error: Table with name bank_customers does not exist!
Did you mean "customers"?

LINE 1: SELECT gender, COUNT(*) AS total_customers FROM bank_customers GROUP BY gender
                                                        ^

## 1. Basic Queries - Explore the Data

In [6]:
query("""
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY bank_name ORDER BY account_balance DESC) AS rank_num
    FROM customers
) t
WHERE rank_num = 1
""")

,customer_id,bank_id,bank_name,account_number,title,first_name,middle_name,last_name,full_name,gender,...,annual_income,primary_source_of_funds,account_type,account_balance,credit_score,account_status,created_date,last_transaction_date,transactions_per_month,rank_num
0,CUST24545047,SBI001,State Bank of India,505213503618,Dr.,Myra,NaN,Yadav,Myra Yadav,Female,...,1413870,Salary,Savings,4999708.28,849,Active,2020-10-04,2026-01-05,84,1
1,CUST34067711,CBI001,Central Bank of India,421092272425,Ms.,Neha,Rani,Gupta,Neha Rani Gupta,Female,...,1272325,Salary,Current,4999922.19,881,Active,2016-05-28,2026-01-13,83,1

In [7]:
# How many total customers are in the database?
query("SELECT count(*) as total_customers from customers")

   total_customers
0           100000

In [8]:
query("SELECT *,ROW_NUMBER() OVER (PARTITION BY bank_name ORDER BY account_balance DESC) AS rnk FROM bank_customers")

CatalogException: Catalog Error: Table with name bank_customers does not exist!
Did you mean "customers"?

LINE 1: ... BY bank_name ORDER BY account_balance DESC) AS rnk FROM bank_customers
                                                                    ^

In [9]:
# Question 2: List all unique bank names in the database
query("Select distinct bank_name from customers")

               bank_name
0  Central Bank of India
1    State Bank of India

In [18]:
# How many customers does each bank have?
query("Select bank_name,count(customer_id) from customers GROUP BY bank_Name")

               bank_name  count(customer_id)
0  Central Bank of India               50021
1    State Bank of India               49979

In [26]:
# What are the different account types available?
query("select distinct account_type, count(*) as count from customers group by account_type order by count" )

  account_type  count
0       Salary  22135
1      Current  26809
2      Savings  51056

In [38]:
# How many male and female customers are there?
query("select gender, count(gender) from customers group by gender")

   gender  count(gender)
0  Female          49994
1    Male          50006

In [40]:
query("select * from customers limit 1")

,customer_id,bank_id,bank_name,account_number,title,first_name,middle_name,last_name,full_name,gender,...,occupation,annual_income,primary_source_of_funds,account_type,account_balance,credit_score,account_status,created_date,last_transaction_date,transactions_per_month
0,CUST28908766,SBI001,State Bank of India,029224648600,Mrs.,Kavita,Dev,Malhotra,Kavita Dev Malhotra,Female,...,Chef,841544,Salary,Savings,392560.75,446,Active,2025-12-31,2026-01-31,109

In [45]:
# List the first 10 customers with their names and email addresses.
query("select full_name, email from customers limit 10")

             full_name                           email
0  Kavita Dev Malhotra  kavita.malhotra589@outlook.com
1   Preeti Kumar Yadav       preeti.yadav653@yahoo.com
2     Sunita Rani Jain   sunita.jain513@rediffmail.com
3        Sakshi Bansal      sakshi.bansal154@gmail.com
4     Aryan Dev Mishra       aryan.mishra863@gmail.com
5      Vivaan Dev Jain   vivaan.jain228@rediffmail.com
6     Neha Mohan Verma    neha.verma252@rediffmail.com
7  Rajesh Shankar Shah      rajesh.shah473@hotmail.com
8         Rohit Bhatia       rohit.bhatia937@yahoo.com
9          Advik Ghosh      advik.ghosh922@outlook.com

In [43]:
query("DESCRIBE customers")

                column_name column_type null   key default extra
0               customer_id     VARCHAR  YES  None    None  None
1                   bank_id     VARCHAR  YES  None    None  None
2                 bank_name     VARCHAR  YES  None    None  None
3            account_number     VARCHAR  YES  None    None  None
4                     title     VARCHAR  YES  None    None  None
5                first_name     VARCHAR  YES  None    None  None
6               middle_name     VARCHAR  YES  None    None  None
7                 last_name     VARCHAR  YES  None    None  None
8                 full_name     VARCHAR  YES  None    None  None
9                    gender     VARCHAR  YES  None    None  None
10            date_of_birth        DATE  YES  None    None  None
11                    email     VARCHAR  YES  None    None  None
12                    phone     VARCHAR  YES  None    None  None
13                  address     VARCHAR  YES  None    None  None
14               occupation     VARCHAR  YES  None    None  None
15            annual_income      BIGINT  YES  None    None  None
16  primary_source_of_funds     VARCHAR  YES  None    None  None
17             account_type     VARCHAR  YES  None    None  None
18          account_balance      DOUBLE  YES  None    None  None
19             credit_score      BIGINT  YES  None    None  None
20           account_status     VARCHAR  YES  None    None  None
21             created_date        DATE  YES  None    None  None
22    last_transaction_date        DATE  YES  None    None  None
23   transactions_per_month      BIGINT  YES  None    None  None

In [51]:
# How many customers have an Active account status?
query("select account_status, count(*) from customers group by account_status")

  account_status  count_star()
0       Inactive         25162
1         Active         74838

In [52]:
# Find all customers who are Doctors.
query("select customer_id, full_name from customers where occupation='Doctor' ")

       customer_id            full_name
0     CUST53768308     Ritu Shree Ghosh
1     CUST58076544   Sandeep Kumar Iyer
2     CUST96169403       Diya Lal Ghosh
3     CUST18627123  Aadhya Shankar Iyer
4     CUST24494221     Advik Bhai Patel
...            ...                  ...
2223  CUST60138661     Advik Devi Sinha
2224  CUST78498627     Rekha Sai Saxena
2225  CUST56557285         Aditya Mehta
2226  CUST43540655   Priya Prasad Singh
2227  CUST95691551      Neha Bala Yadav

[2228 rows x 2 columns]

In [6]:
# What is the highest account balance in the database?
query("select full_name, max(account_balance) as bal from customers group by full_name order by bal desc")

                  full_name         bal
0           Neha Rani Gupta  4999922.19
1         Pooja Anand Ghosh  4999912.51
2                Myra Yadav  4999708.28
3                 Pooja Rao  4999706.44
4          Anvi Rani Tiwari  4999488.26
...                     ...         ...
45767      Ravi Bhai Bhatia     5350.56
45768    Simran Devi Chopra     5348.33
45769   Kabir Narayan Joshi     5305.17
45770    Shweta Prakash Sen     5177.62
45771  Siddharth Rani Patel     5133.44

[45772 rows x 2 columns]

In [9]:
# List all unique occupations in alphabetical order.
query("select distinct occupation from customers order by occupation ASC")

              occupation
0             Accountant
1              Architect
2           Army Officer
3                 Banker
4         Business Owner
5              Carpenter
6   Chartered Accountant
7                   Chef
8         Civil Engineer
9             Consultant
10        Content Writer
11          Data Analyst
12              Designer
13                Doctor
14                Driver
15           Electrician
16          Entrepreneur
17        Factory Worker
18                Farmer
19   Government Employee
20            HR Manager
21             Homemaker
22       Insurance Agent
23            Journalist
24                Lawyer
25     Marketing Manager
26   Mechanical Engineer
27                 Nurse
28            Pharmacist
29          Photographer
30                 Pilot
31               Plumber
32        Police Officer
33             Professor
34       Project Manager
35     Real Estate Agent
36        Retail Manager
37               Retired
38         Sales Manager
39             Scientist
40            Shopkeeper
41     Software Engineer
42               Student
43               Teacher

In [14]:
# How many customers have a Savings account?
query("select count(*) from customers where account_type='Savings' ")

   count_star()
0         51056

In [19]:
# Find customers with account balance greater than 10 lakhs.
query("select customer_id, full_name,count(*) as ct from customers where account_balance>1000000 group by customer_id,full_name")

        customer_id                full_name  ct
0      CUST58076544       Sandeep Kumar Iyer   1
1      CUST47595965  Mahesh Shankar Krishnan   1
2      CUST87415777        Rahul Narayan Rao   1
3      CUST47313652      Ramesh Prasad Menon   1
4      CUST43809364         Ramesh Chowdhury   1
...             ...                      ...  ..
45648  CUST16814968              Ishita Shah   1
45649  CUST61656686         Saanvi Nath Iyer   1
45650  CUST95078022            Anika Lal Das   1
45651  CUST87346741          Rekha Chowdhury   1
45652  CUST30080983     Deepak Prasad Tiwari   1

[45653 rows x 3 columns]

In [24]:
# What are the different primary sources of funds?
query("SELECT DISTINCT primary_source_of_funds, COUNT(*) as count FROM customers GROUP BY primary_source_of_funds ORDER BY count DESC")

  primary_source_of_funds  count
0                  Salary  69566
1     Professional Income  11185
2         Business Income   6851
3          Family Support   3389
4      Investment Returns   3355
5                 Pension   2295
6     Agricultural Income   2261
7             Scholarship   1098

In [26]:
# List customers from State Bank of India only.
query("select customer_id, full_name from customers where bank_name = 'State Bank of India' ")

        customer_id             full_name
0      CUST28908766   Kavita Dev Malhotra
1      CUST93976837    Preeti Kumar Yadav
2      CUST61096350         Sakshi Bansal
3      CUST26308983      Neha Mohan Verma
4      CUST96399069   Rajesh Shankar Shah
...             ...                   ...
49974  CUST10294710     Sandeep Chowdhury
49975  CUST14968854      Geeta Dev Rajput
49976  CUST21357325  Pooja Bala Chowdhury
49977  CUST36002404   Sandeep Mohan Joshi
49978  CUST95865386      Varun Anand Shah

[49979 rows x 2 columns]

In [28]:
# What is the average account balance across all customers?
query("select round(avg(account_balance),2) from customers ")

   round(avg(account_balance), 2)
0                       1307177.4

In [29]:
# What is the average annual income by gender?
query("select gender,round(avg(annual_income),2) as avg_ann from customers group by gender order by avg_ann")

   gender     avg_ann
0    Male  1061494.85
1  Female  1069039.31

In [34]:
# Find the top 10 highest-paid occupations by average income.
query("select occupation,round(avg(annual_income),2) as new, count(*) from customers group by occupation order by new DESC limit 10")

             occupation         new  count_star()
0        Business Owner  5187198.13          2273
1          Entrepreneur  4033795.28          2315
2                 Pilot  3225061.19          2387
3                Doctor  2924540.14          2228
4                Lawyer  1766554.00          2203
5       Project Manager  1640822.24          2353
6            Consultant  1613237.55          2276
7     Software Engineer  1533794.05          2247
8  Chartered Accountant  1294242.44          2251
9             Architect  1258107.16          2227

In [36]:
# What is the average account balance for each account type?
query("select account_type, avg(account_balance) from customers group by account_type")

  account_type  avg(account_balance)
0       Salary          1.303526e+06
1      Current          1.416604e+06
2      Savings          1.251302e+06

In [ ]:
# How many customers are there in each occupation category?
query("select occupation,count(full_name) from customers group by occupation order by ")

              occupation  count(full_name)
0         Business Owner              2273
1      Real Estate Agent              2247
2               Designer              2253
3                 Driver              2342
4              Scientist              2268
5        Project Manager              2353
6    Government Employee              2327
7         Civil Engineer              2293
8         Content Writer              2310
9             HR Manager              2327
10             Carpenter              2266
11             Homemaker              2257
12            Pharmacist              2295
13             Architect              2227
14                Lawyer              2203
15                 Nurse              2206
16             Professor              2230
17       Insurance Agent              2330
18            Consultant              2276
19                Banker              2270
20           Electrician              2203
21                Farmer              2261
22          Entrepreneur              2315
23          Data Analyst              2227
24     Software Engineer              2247
25  Chartered Accountant              2251
26         Sales Manager              2270
27          Army Officer              2292
28            Shopkeeper              2263
29          Photographer              2154
30                  Chef              2335
31            Accountant              2289
32               Retired              2295
33               Student              2230
34        Retail Manager              2243
35               Teacher              2253
36   Mechanical Engineer              2204
37                Doctor              2228
38               Plumber              2399
39     Marketing Manager              2280
40        Factory Worker              2284
41                 Pilot              2387
42        Police Officer              2285
43            Journalist              2252

In [2]:
# Find customers with credit score above 800.
query("select full_name, credit_score from customers where credit_score>800 order by credit_score desc")

                   full_name  credit_score
0               Sara Chauhan           900
1        Vijay Dev Chowdhury           900
2              Krishna Mehta           900
3        Reyansh Bala Pandey           900
4                Ayaan Menon           900
...                      ...           ...
16470     Vikas Prakash Jain           801
16471  Ananya Chandra Pandey           801
16472      Priya Narayan Sen           801
16473      Meera Lakshmi Rao           801
16474         Sara Anand Sen           801

[16475 rows x 2 columns]

In [13]:
# What is the total deposit amount in each bank?
query("select bank_name,round(sum(account_balance),2) as sum,count(*) from customers group by bank_name order by sum desc ")

               bank_name           sum  count_star()
0  Central Bank of India  6.552683e+10         50021
1    State Bank of India  6.519091e+10         49979

In [15]:
query("select * from customers where occupation = 'Retired' limit 1")

,customer_id,bank_id,bank_name,account_number,title,first_name,middle_name,last_name,full_name,gender,...,occupation,annual_income,primary_source_of_funds,account_type,account_balance,credit_score,account_status,created_date,last_transaction_date,transactions_per_month
0,CUST75337453,SBI001,State Bank of India,732064107975,Dr.,Pallavi,Prakash,Nair,Pallavi Prakash Nair,Female,...,Retired,271588,Pension,Salary,373706.75,495,Active,2025-07-02,2025-12-11,126

In [18]:
# Find all customers who are Students or Retired.
query("Select * from customers where occupation in ('Retired', 'Students') limit 5")

,customer_id,bank_id,bank_name,account_number,title,first_name,middle_name,last_name,full_name,gender,...,occupation,annual_income,primary_source_of_funds,account_type,account_balance,credit_score,account_status,created_date,last_transaction_date,transactions_per_month
0,CUST75337453,SBI001,State Bank of India,732064107975,Dr.,Pallavi,Prakash,Nair,Pallavi Prakash Nair,Female,...,Retired,271588,Pension,Salary,373706.75,495,Active,2025-07-02,2025-12-11,126
1,CUST32732329,SBI001,State Bank of India,688892448457,Er.,Nikhil,Chandra,Bhatia,Nikhil Chandra Bhatia,Male,...,Retired,125700,Pension,Savings,27482.07,772,Active,2018-11-25,2026-03-03,50
2,CUST85810873,SBI001,State Bank of India,104917708992,Dr.,Suresh,NaN,Menon,Suresh Menon,Male,...,Retired,432434,Pension,Salary,37381.71,311,Active,2018-11-07,2026-01-23,33
3,CUST12144973,SBI001,State Bank of India,112247861324,Er.,Shaurya,NaN,Mehta,Shaurya Mehta,Male,...,Retired,264428,Pension,Salary,491315.77,666,Inactive,2026-02-25,2025-02-01,36
4,CUST69500779,CBI001,Central Bank of India,940638428517,Ms.,Megha,NaN,Shah,Megha Shah,Female,...,Retired,594971,Pension,Savings,775094.41,806,Active,2018-06-11,2026-02-15,118

In [ ]:
# What percentage of customers have Active vs Inactive accounts?
query("select account_status, count(*) as perc from customers where account_status in ('Active','Inactive') group by account_status")

  account_status   perc
0       Inactive  25162
1         Active  74838

In [15]:
query("SELECT account_status,COUNT(*) as count,ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) as percentage FROM customers GROUP BY account_status")

  account_status  count  percentage
0       Inactive  25162       25.16
1         Active  74838       74.84

In [19]:
# find the percenatge of active and inactive records
query("select account_status, round(count(*)*100/(Select count(*) from customers),2) as perc from customers where account_status in ('Active','Inactive') group by account_status")

  account_status   perc
0         Active  74.84
1       Inactive  25.16

In [27]:
# find the percenatge of active and inactive records
query("select account_status, round(count(*)*100 / Sum (count(*)) over(),2) as perc from customers where account_status in ('Active','Inactive') group by account_status")

  account_status   perc
0       Inactive  25.16
1         Active  74.84

In [33]:
# Find the average credit score by account type.
query("select account_type, round(avg(credit_score),2), count(*) as avg from customers group by account_type")

  account_type  round(avg(credit_score), 2)    avg
0      Savings                       600.15  51056
1       Salary                       599.99  22135
2      Current                       599.16  26809

In [36]:
# List customers with annual income between 5 lakhs and 10 lakhs.
query("select full_name, annual_income from customers where annual_income between 500000 and 1000000 limit 20")

               full_name  annual_income
0    Kavita Dev Malhotra         841544
1        Vivaan Dev Jain         551407
2        Varun Shree Sen         821918
3          Vivaan Bansal         607332
4       Neha Rani Tiwari         542761
5          Kritika Desai         619450
6    Megha Lakshmi Kumar         894737
7   Karan Shankar Bhatia         979217
8       Sunita Lal Menon         852154
9       Ravi Rani Bansal         605549
10  Ishita Shankar Gupta         767180
11            Varun Nair         909777
12        Ajay Mukherjee         518744
13   Ishita Shree Chopra         722347
14          Sunita Mehta         593724
15     Rekha Bhai Bansal         731414
16          Ishita Sinha         708518
17   Riya Lakshmi Bhatia         855115
18           Divya Gupta         666856
19           Rohan Mehta         626039

In [38]:
query("describe customers")

                column_name column_type null   key default extra
0               customer_id     VARCHAR  YES  None    None  None
1                   bank_id     VARCHAR  YES  None    None  None
2                 bank_name     VARCHAR  YES  None    None  None
3            account_number     VARCHAR  YES  None    None  None
4                     title     VARCHAR  YES  None    None  None
5                first_name     VARCHAR  YES  None    None  None
6               middle_name     VARCHAR  YES  None    None  None
7                 last_name     VARCHAR  YES  None    None  None
8                 full_name     VARCHAR  YES  None    None  None
9                    gender     VARCHAR  YES  None    None  None
10            date_of_birth        DATE  YES  None    None  None
11                    email     VARCHAR  YES  None    None  None
12                    phone     VARCHAR  YES  None    None  None
13                  address     VARCHAR  YES  None    None  None
14               occupation     VARCHAR  YES  None    None  None
15            annual_income      BIGINT  YES  None    None  None
16  primary_source_of_funds     VARCHAR  YES  None    None  None
17             account_type     VARCHAR  YES  None    None  None
18          account_balance      DOUBLE  YES  None    None  None
19             credit_score      BIGINT  YES  None    None  None
20           account_status     VARCHAR  YES  None    None  None
21             created_date        DATE  YES  None    None  None
22    last_transaction_date        DATE  YES  None    None  None
23   transactions_per_month      BIGINT  YES  None    None  None

In [41]:
# How many customers have each title (Mr., Mrs., Ms., Dr., Er.)?
query("select title,count(*) from customers group by title")

  title  count_star()
0  Mrs.         16396
1   Er.         16675
2   Dr.         33376
3   Ms.         16649
4   Mr.         16904

In [47]:
# Find customers whose primary source of funds is Business Income.
query("select * from customers where primary_source_of_funds = 'Business Income' limit 5")

,customer_id,bank_id,bank_name,account_number,title,first_name,middle_name,last_name,full_name,gender,...,occupation,annual_income,primary_source_of_funds,account_type,account_balance,credit_score,account_status,created_date,last_transaction_date,transactions_per_month
0,CUST39266156,CBI001,Central Bank of India,330010008120,Dr.,Sunita,Rani,Jain,Sunita Rani Jain,Female,...,Business Owner,1127813,Business Income,Current,766680.71,360,Active,2025-02-18,2026-01-14,64
1,CUST57810402,SBI001,State Bank of India,051060672503,Dr.,Pari,Prasad,Naidu,Pari Prasad Naidu,Female,...,Business Owner,4860360,Business Income,Current,4358965.08,347,Inactive,2019-08-07,2024-08-31,6
2,CUST26384961,CBI001,Central Bank of India,612177996117,Ms.,Myra,Kumar,Nair,Myra Kumar Nair,Female,...,Shopkeeper,214105,Business Income,Current,493423.87,634,Active,2017-03-10,2026-01-31,109
3,CUST19514021,SBI001,State Bank of India,517157428010,Er.,Kabir,NaN,Bose,Kabir Bose,Male,...,Shopkeeper,928584,Business Income,Current,1944596.42,314,Inactive,2021-09-11,2024-04-24,85
4,CUST57437808,SBI001,State Bank of India,634403133343,Ms.,Myra,Prasad,Kapoor,Myra Prasad Kapoor,Female,...,Entrepreneur,2610469,Business Income,Current,4555286.73,805,Active,2016-05-30,2025-12-29,150

In [59]:
# What is the average number of transactions per month by account type?
query("select account_type, round(avg(transactions_per_month),2), count(*) from customers group by account_type")

  account_type  round(avg(transactions_per_month), 2)  count_star()
0       Salary                                  77.42         22135
1      Savings                                  77.71         51056
2      Current                                  77.42         26809

In [64]:
# Find customers with zero annual income.
query("select * from customers where annual_income = 0")

,customer_id,bank_id,bank_name,account_number,title,first_name,middle_name,last_name,full_name,gender,...,occupation,annual_income,primary_source_of_funds,account_type,account_balance,credit_score,account_status,created_date,last_transaction_date,transactions_per_month
0,CUST16507206,CBI001,Central Bank of India,627989263025,Mr.,Vihaan,Kumar,Desai,Vihaan Kumar Desai,Male,...,Homemaker,0,Family Support,Savings,81827.68,352,Active,2018-02-26,2026-01-16,136
1,CUST17958444,SBI001,State Bank of India,333145235655,Dr.,Ritu,Sai,Verma,Ritu Sai Verma,Female,...,Homemaker,0,Family Support,Savings,76625.09,724,Active,2018-02-09,2025-12-31,118
2,CUST85619011,CBI001,Central Bank of India,663495493218,Ms.,Anjali,NaN,Mehta,Anjali Mehta,Female,...,Homemaker,0,Family Support,Savings,454485.17,865,Active,2016-04-02,2026-01-04,68
3,CUST66816196,SBI001,State Bank of India,048056630861,Mr.,Sai,Prasad,Krishnan,Sai Prasad Krishnan,Male,...,Homemaker,0,Family Support,Savings,145841.31,304,Active,2021-07-10,2025-12-06,132
4,CUST76858764,SBI001,State Bank of India,034940623463,Er.,Aarav,NaN,Iyer,Aarav Iyer,Male,...,Homemaker,0,Family Support,Savings,109745.16,342,Active,2016-05-25,2026-01-14,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2252,CUST47860005,CBI001,Central Bank of India,337575701454,Er.,Shaurya,Anand,Sen,Shaurya Anand Sen,Male,...,Homemaker,0,Family Support,Savings,301372.82,327,Inactive,2025-02-27,2024-08-14,143
2253,CUST55678542,SBI001,State Bank of India,671729720336,Dr.,Anika,NaN,Malhotra,Anika Malhotra,Female,...,Homemaker,0,Family Support,Savings,436219.24,429,Active,2025-04-22,2025-12-25,122
2254,CUST48879023,CBI001,Central Bank of India,207230044156,Er.,Rohit,Bhai,Joshi,Rohit Bhai Joshi,Male,...,Homemaker,0,Family Support,Savings,274758.24,372,Active,2022-10-01,2026-01-16,147
2255,CUST62976229,SBI001,State Bank of India,347751237387,Er.,Suresh,Kumari,Rajput,Suresh Kumari Rajput,Male,...,Homemaker,0,Family Support,Savings,146522.17,496,Active,2024-11-19,2025-12-08,25
2256,CUST95865386,SBI001,State Bank of India,377603047651,Er.,Varun,Anand,Shah,Varun Anand Shah,Male,...,Homemaker,0,Family Support,Savings,465276.27,322,Active,2016-10-22,2026-01-17,79

In [67]:
# What is the average account balance by gender and account type?
query("select distinct gender, account_type,round(avg(account_balance),2), count(*) from customers group by gender, account_type")

   gender account_type  round(avg(account_balance), 2)  count_star()
0  Female      Savings                      1257267.88         25534
1  Female       Salary                      1313599.97         11022
2    Male       Salary                      1293534.67         11113
3    Male      Current                      1408769.64         13371
4  Female      Current                      1424398.77         13438
5    Male      Savings                      1245332.77         25522

In [74]:
query("describe customers")

                column_name column_type null   key default extra
0               customer_id     VARCHAR  YES  None    None  None
1                   bank_id     VARCHAR  YES  None    None  None
2                 bank_name     VARCHAR  YES  None    None  None
3            account_number     VARCHAR  YES  None    None  None
4                     title     VARCHAR  YES  None    None  None
5                first_name     VARCHAR  YES  None    None  None
6               middle_name     VARCHAR  YES  None    None  None
7                 last_name     VARCHAR  YES  None    None  None
8                 full_name     VARCHAR  YES  None    None  None
9                    gender     VARCHAR  YES  None    None  None
10            date_of_birth        DATE  YES  None    None  None
11                    email     VARCHAR  YES  None    None  None
12                    phone     VARCHAR  YES  None    None  None
13                  address     VARCHAR  YES  None    None  None
14               occupation     VARCHAR  YES  None    None  None
15            annual_income      BIGINT  YES  None    None  None
16  primary_source_of_funds     VARCHAR  YES  None    None  None
17             account_type     VARCHAR  YES  None    None  None
18          account_balance      DOUBLE  YES  None    None  None
19             credit_score      BIGINT  YES  None    None  None
20           account_status     VARCHAR  YES  None    None  None
21             created_date        DATE  YES  None    None  None
22    last_transaction_date        DATE  YES  None    None  None
23   transactions_per_month      BIGINT  YES  None    None  None

In [ ]:
#  Find the youngest and oldest customers in the database.
query("select youngest as category, full_name from customers order by date_of_birth")